### ISSUE TITLE
Update to yaml@2

### ISSUE THREAD

**Issue by guimard** [tapjs/tap-yaml#11]
Hi,

do you plan to update tap-yaml to use yaml@2 ? Its API changed and current tap-yaml isn't compatible with it.

Cheers,
Yadd

**Comment by isaacs** [comment]
Blocked by https://github.com/eemeli/yaml/issues/457

I'm eager to get to it, since I do intend to refactor this module into typescript like I'm doing with the rest of node-tap.

But, this module uses a bunch of custom types.  The YAML v2 API appears to be much improved, but I can't work out how to do custom object/map types, and reporting Error objects in a nice way is a pretty important thing for a test framework.

**Comment by isaacs** [comment]
Done.
